# @format

version: "3.9"
services:
  db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password123
    networks:
      - backend
    container_name: database
  node:
    build: ./
    restart: always
    ports:
      - "80:3000"
    environment:
      - db_path=mongodb://root:password123@database:27017/
      - PORT=3000
    depends_on:
      - db
    networks:
      - backend
    container_name: api
networks:
  backend:
    driver: bridge
